# Generated by Django 3.1 on 2020-08-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextInput',
            new_name='Text_Result',
        ),
    ]
